---
title: "Tommy Conkling & Jacob Cargal-Bley PUBPOL 543 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(sf)
library(tidyverse)
library(scales)
library(grid)
library(scales)
library(viridis)
```

```{r}
#load Conkling's files
myWeb="https://github.com/tconkling47/543_dashboard/raw/main/"
boxplot=readRDS(file=url(paste0(myWeb,"boxplot.rds")))
boxplot_image="https://github.com/tconkling47/543_dashboard/raw/main/Conkling_Bivariate_Cat-Numerical_Graph_PUBPOL543.jpg" 
univariate=readRDS(file=url(paste0(myWeb,"univariate.rds")))
univariate_image = "https://github.com/tconkling47/543_dashboard/raw/main/Conkling_Univariate_PUBPOL543.jpg"
interactive_map=readRDS(file=url(paste0(myWeb,"interactive_map.rds")))
```

Conkling: Public Universities are the Best Financial Choice for B.A. Degrees
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Average Undergraduate Student Debt at U.S. Flagship Public Universities

```{r}
interactive_map
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

